//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.03 at 07:24:49 PM EEST 
//


package translate;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="entry" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="english" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="italian" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="romanian" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="spanish" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="german" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="french" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entry"
})
@XmlRootElement(name = "dictionary")
public class Dictionary {

    @XmlElement(required = true)
    protected List<Dictionary.Entry> entry;

    /**
     * Gets the value of the entry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dictionary.Entry }
     * 
     * 
     */
    public List<Dictionary.Entry> getEntry() {
        if (entry == null) {
            entry = new ArrayList<Dictionary.Entry>();
        }
        return this.entry;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="english" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="italian" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="romanian" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="spanish" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="german" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="french" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "english",
        "italian",
        "romanian",
        "spanish",
        "german",
        "french"
    })
    public static class Entry {

        @XmlElement(required = true)
        protected String english;
        @XmlElement(required = true)
        protected String italian;
        @XmlElement(required = true)
        protected String romanian;
        @XmlElement(required = true)
        protected String spanish;
        @XmlElement(required = true)
        protected String german;
        @XmlElement(required = true)
        protected String french;

        /**
         * Gets the value of the english property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnglish() {
            return english;
        }

        /**
         * Sets the value of the english property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnglish(String value) {
            this.english = value;
        }

        /**
         * Gets the value of the italian property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItalian() {
            return italian;
        }

        /**
         * Sets the value of the italian property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItalian(String value) {
            this.italian = value;
        }

        /**
         * Gets the value of the romanian property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRomanian() {
            return romanian;
        }

        /**
         * Sets the value of the romanian property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRomanian(String value) {
            this.romanian = value;
        }

        /**
         * Gets the value of the spanish property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpanish() {
            return spanish;
        }

        /**
         * Sets the value of the spanish property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpanish(String value) {
            this.spanish = value;
        }

        /**
         * Gets the value of the german property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGerman() {
            return german;
        }

        /**
         * Sets the value of the german property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGerman(String value) {
            this.german = value;
        }

        /**
         * Gets the value of the french property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrench() {
            return french;
        }

        /**
         * Sets the value of the french property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrench(String value) {
            this.french = value;
        }

    }

}
